### ISSUE TITLE
garage repairing cars

### ISSUE THREAD

**Issue by fuse9** [JonasDev17/qb-garages#55]
the garage seems to be repairing cars to 100% after every server restart

**Comment by 6utzeit** [comment]
I can confirm this.

**Comment by SlimChances** [comment]
I can confirm too

**Comment by JonasDev17** [comment]
The issue is that if a person stores their vehicle after fixing it the current state of the vehicle is updated in the database. Now if the player crashes the car and leaves it broken outside, the vehicle won't be updated in the database until it gets parked. So if the player never parks their vehicle, the state in the database will never update and after server restart the vehicle is back in the garage but with the old state which was when the player parked it the last time which was after fixing the vehicle.

**Comment by RebelFinatic** [comment]
It would be pretty dope if it stored the current vehicle damage info into the database at a given interval that way even when parked it would have the correct vehicle damage info, just an idea.

**Comment by zeiglermensch** [comment]
> It would be pretty dope if it stored the current vehicle damage info into the database at a given interval that way even when parked it would have the correct vehicle damage info, just an idea.

This would be best accomplished in your vehicle damage script to store the damage at an interval as the player is driving it.  That being said, it could cause undue stress on your SQL database if you have a large player base driving around.
